In [4]:
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

In [3]:
input_data.read_data_sets('MNIST_data/', one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7fa65109f358>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7fa6510a0860>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7fa6510eefd0>)

In [33]:
x= np.array([1,2,3,4,5,6])
print(x)
x = np.reshape(x, (-1,1))
print(x)
# x.ravel()
x.flatten()

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


array([1, 2, 3, 4, 5, 6])